### ISSUE TITLE
Results Generated Unrelated to URL

### ISSUE THREAD

**Issue by raray** [nystudio107/rollup-plugin-critical#16]
### Question
I am highly confused about the results I am seeing. I've tried multiple different `criticalUrl` values. I've even used the exact example config from the docs. No matter what I put in, I get this CSS generated:
```css
@charset "UTF-8";@import url(https://use.typekit.net/fbe6xqa.css);@font-face{font-family:AvenirNextVariable;src:url(/assets/fonts/AvenirNextVariableRoman.woff) format("woff-variations"),url(/assets/fonts/AvenirNextVariableRoman.woff2) format("woff2-variations");font-weight:400 900;font-stretch:75% 100%;font-style:normal;font-display:swap}@font-face{font-family:AvenirNextVariable;src:url(/assets/fonts/AvenirNextVariableItalic.woff) format("woff-variations"),url(/assets/fonts/AvenirNextVariableItalic.woff2) format("woff2-variations");font-weight:400 900;font-stretch:75% 100%;font-style:italic;font-display:swap}
```

### Additional context
- Running locally.
- That typekit, and those type styles, are from my local project.
- I see the following logs:
  
  ```
  Generating critical CSS from https://nystudio107.com/ to index_critical.min.css
  Generating critical CSS from https://nystudio107.com/about to about/index_critical.min.css
  ```
